version: "3.8"

services:
  # BACK
  back:
    build: ./personal-website-builder-back
    volumes:
      - ./personal-website-builder-back/src:/usr/src/app/src
      - ./personal-website-builder-back/prisma:/usr/src/app/prisma
      - ./personal-website-builder-back/package.json:/usr/src/app/package.json
      - ./personal-website-builder-back/package-lock.json:/usr/src/app/package-lock.json
    depends_on:
      - postgres
    command: npm run start:debug
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/personal-website-builder
      - JWT_SECRET=mysecretkey
      - JWT_REFRESH_SECRET=myrefreshsecretkey
    ports:
      - "3000:3000"
      - "9229:9229"

  # FRONT
  front:
    build: ./personal-website-builder-front
    volumes:
      - ./personal-website-builder-front/src:/usr/src/app/src
    command: npm run start
    ports:
      - "4200:4200"
    depends_on:
      - back

  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: personal-website-builder
    ports:
      - "5432:5432"
  
  postgres-test:
    image: postgres:16.3
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5433:5432"
    
