version: "3"

services:
  # BACK
  back:
    build: ./personal-website-builder-back
    volumes:
      - ./personal-website-builder-back:/usr/src/app
    command: node_modules/.bin/nest start --debug 0.0.0.0:9229 --watch
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
      - "9229:9229"
